# Generated by Django 6.0.1 on 2026-04-13 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
