# Generated by Django 6.0.2 on 2026-03-09 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('companyname', models.CharField(max_length=150)),
                ('jobtitle', models.CharField(max_length=150)),
                ('location', models.CharField(blank=True, max_length=150, null=True)),
                ('salary', models.CharField(blank=True, max_length=100, null=True)),
                ('postedat', models.DateTimeField(auto_now_add=True)),
                ('link_to_apply', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'jobs',
            },
        ),
    ]
