# Generated by Django 6.0.1 on 2026-03-10 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.IntegerField(default=0, unique=True)),
                ('APP_ID', models.AutoField(primary_key=True, serialize=False)),
                ('jobrole', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('Applied', 'Applied'), ('Interview', 'Interview'), ('Offered', 'Offered'), ('Rejected', 'Rejected')], default='Applied', max_length=50)),
                ('changed_at', models.DateTimeField(auto_now=True)),
                ('link', models.TextField(blank=True, null=True)),
                ('company', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'application',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('U_ID', models.AutoField(primary_key=True, serialize=False)),
                ('uname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password_hash', models.TextField()),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('email_id', models.AutoField(primary_key=True, serialize=False)),
                ('sender', models.CharField(blank=True, max_length=255, null=True)),
                ('emailbody', models.TextField(blank=True, null=True)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('emaildate', models.DateTimeField(auto_now_add=True)),
                ('detected_status', models.CharField(blank=True, max_length=100, null=True)),
                ('APP_ID', models.ForeignKey(db_column='APP_ID', on_delete=django.db.models.deletion.CASCADE, to='appointment.application')),
            ],
            options={
                'db_table': 'email',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('blogtext', models.TextField(blank=True, null=True)),
                ('U_ID', models.ForeignKey(db_column='U_ID', on_delete=django.db.models.deletion.CASCADE, to='appointment.user')),
            ],
            options={
                'db_table': 'blog',
            },
        ),
        migrations.AddField(
            model_name='application',
            name='U_ID',
            field=models.ForeignKey(db_column='U_ID', on_delete=django.db.models.deletion.CASCADE, to='appointment.user'),
        ),
    ]
