"""
Django settings for core project.

Generated by 'django-admin startproject' using Django.

This configuration supports:

* Django REST Framework
* Next.js frontend (CORS enabled)
* Environment variables (.env)
* Production-ready database via dj_database_url
  """

from pathlib import Path
import os
from dotenv import load_dotenv
import dj_database_url
from datetime import timedelta
# Load environment variables

load_dotenv()

# Base directory

BASE_DIR = Path(__file__).resolve().parent.parent

# ================================

# SECURITY

# ================================
GOOGLE_CLIENT_ID = os.getenv("GOOGLE_CLIENT_ID")
SECRET_KEY = os.getenv("SECRET_KEY")

DEBUG = os.getenv("DEBUG") == "True"

ALLOWED_HOSTS = ['*']

# Get credentials
GMAIL_CREDENTIALS_PATH = os.path.join(BASE_DIR, 'credentials.json')
GMAIL_TOKEN_PATH = os.path.join(BASE_DIR, 'token.json')

# ================================

# APPLICATIONS

# ================================

INSTALLED_APPS = [
'django.contrib.admin',
'django.contrib.auth',
'django.contrib.contenttypes',
'django.contrib.sessions',
'django.contrib.messages',
'django.contrib.staticfiles',

# Third party
'rest_framework',
'corsheaders',

# Local apps
'application',
'job_roles',
'job_scraper',

'user',
'emails',
'blog',
'gmail',


]

# ================================

# MIDDLEWARE

# ================================

MIDDLEWARE = [
'corsheaders.middleware.CorsMiddleware',

'django.middleware.security.SecurityMiddleware',
'django.contrib.sessions.middleware.SessionMiddleware',
'django.middleware.common.CommonMiddleware',

'django.middleware.csrf.CsrfViewMiddleware',
'django.contrib.auth.middleware.AuthenticationMiddleware',

'django.contrib.messages.middleware.MessageMiddleware',
'django.middleware.clickjacking.XFrameOptionsMiddleware',


]

# ================================

# URLS / WSGI

# ================================

ROOT_URLCONF = 'core.urls'

WSGI_APPLICATION = 'core.wsgi.application'

# ================================

# TEMPLATES

# ================================

TEMPLATES = [
{
'BACKEND': 'django.template.backends.django.DjangoTemplates',
'DIRS': [],
'APP_DIRS': True,
'OPTIONS': {
'context_processors': [
'django.template.context_processors.request',
'django.contrib.auth.context_processors.auth',
'django.contrib.messages.context_processors.messages',
],
},
},
]

# ================================

# DATABASE

# ================================

DATABASES = {
"default": dj_database_url.parse(
url=os.getenv("DATABASE_URL", ""),
conn_max_age=600,
conn_health_checks=True
)
}

# ================================

# PASSWORD VALIDATION

# ================================

AUTH_PASSWORD_VALIDATORS = [
{
'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
},
{
'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
},
{
'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
},
{
'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
},
]

# ================================

# INTERNATIONALIZATION

# ================================

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# ================================

# STATIC FILES

# ================================

STATIC_URL = 'static/'

# ================================

# CORS SETTINGS (FOR NEXT.JS)

# ================================
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
]

CORS_ALLOW_CREDENTIALS = True
# ================================

# DJANGO REST FRAMEWORK SETTINGS

# ================================

REST_FRAMEWORK = {
'DEFAULT_PERMISSION_CLASSES': [
'rest_framework.permissions.AllowAny',
],

"DEFAULT_AUTHENTICATION_CLASSES": (
        "user.authentication.CookieJWTAuthentication",
    ),


}

# ================================

# DEFAULT PRIMARY KEY

# ================================

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'user.User'

SIMPLE_JWT = {
    "USER_ID_FIELD": "U_ID",
    "USER_ID_CLAIM": "user_id",
}
