# Generated by Django 6.0.2 on 2026-03-09 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Jobs',
        ),
        migrations.RemoveField(
            model_name='application',
            name='id',
        ),
    ]
