# Generated by Django 6.0.1 on 2026-03-10 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('salary', models.CharField(blank=True, default='Not Disclosed', max_length=100)),
                ('experience', models.CharField(blank=True, max_length=100)),
                ('posted_on', models.CharField(blank=True, max_length=100)),
                ('job_url', models.URLField(max_length=500, unique=True)),
                ('source', models.CharField(default='Internshala', max_length=100)),
                ('query', models.CharField(blank=True, max_length=100)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Scraped Job',
                'verbose_name_plural': 'Scraped Jobs',
                'ordering': ['-scraped_at'],
            },
        ),
    ]
