
# job_scraper/serializers.py

from rest_framework import serializers
from .models import ScrapedJob


# ──────────────────────────────────────────────────────────
# VIVA EXPLANATION:
# ─────────────────
# What is a Serializer?
#   Converts complex data types (Django Model objects)
#   into Python dicts → then into JSON for API response
#
# Also works in reverse:
#   JSON (from request) → Python dict → Django Model
#
# Think of it as a "translator" between DB and API
#
# ModelSerializer:
#   Automatically generates fields from the Model
#   No need to manually define each field
# ──────────────────────────────────────────────────────────


class ScrapedJobSerializer(serializers.ModelSerializer):

    class Meta:
        model = ScrapedJob         # Which model to serialize
        fields = [                 # Which fields to include in JSON response
            "id",
            "title",
            "company",
            "location",
            "salary",
            "experience",
            "posted_on",
            "job_url",
            "source",
            "query",
            "scraped_at",
        ]
        read_only_fields = ["id", "scraped_at"]
        # VIVA: read_only_fields means these cannot be set by the user
        # They are auto-generated by the system
